version: '3.4'

services:
  cherryit_components:
    container_name: cherryit_components
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    restart: always
    ports:
      - "3000:3000"
    volumes:
    - .:/home/node
    